# Generated by Django 5.2.6 on 2025-09-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='PemainBola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaPemainBola', models.CharField(max_length=10)),
                ('nomorPunggung', models.IntegerField()),
                ('pemainInti', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
