# Generated by Django 5.2.6 on 2025-09-22 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pemainbola_delete_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PemainBola',
        ),
    ]
