# Generated by Django 5.2.6 on 2025-09-30 21:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('futsal', 'Futsal'), ('sepakbola', 'Sepak Bola'), ('badminton', 'Badminton'), ('basket', 'Basket'), ('voli', 'Voli'), ('tenis', 'Tenis'), ('other', 'Other')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
